version: "3.8"

services:
  rodrigo_pg:
    image: postgres:15.1
    container_name: rodrigo_pg
    restart: always
    environment:
      POSTGRES_USER: argos_user
      POSTGRES_PASSWORD: secret1234
      POSTGRES_DB: argos_db
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
