export enum TYPEOFSERVICE {
    TRANSPORTE_PUBLICO = 'Transporte Público',
    VEHICULO_PRIVADO = 'Vehículo Privado',
    SERVICIO_DE_EMERGENCIA = 'Servicio de Emergencia',
    SERVICIO_DE_ENTREGA = 'Servicio de Entrega',
    USO_COMERCIAL = 'Uso Comercial',
    USO_PERSONAL = 'Uso Personal',
    AUTO_DE_ALQUILER = 'Auto de Alquiler',
    COMPARTIR_VIAJE = 'Compartir Viaje', // Por ejemplo, Uber, Lyft
    OTRO = 'Otro',
}

export enum VEHICLEBRAND {
    CHEVROLET = 'Chevrolet',
    VOLKSWAGEN = 'Volkswagen',
    NISSAN = 'Nissan',
    TOYOTA = 'Toyota',
    FORD = 'Ford',
    FIAT = 'Fiat',
    RENAULT = 'Renault',
    HONDA = 'Honda',
    HYUNDAI = 'Hyundai',
    PEUGEOT = 'Peugeot',
    CITROEN = 'Citroën',
    KIA = 'Kia',
    MITSUBISHI = 'Mitsubishi',
    MAZDA = 'Mazda',
    SUBARU = 'Subaru',
    SUZUKI = 'Suzuki',
    JEEP = 'Jeep',
    BMW = 'BMW',
    MERCEDES_BENZ = 'Mercedes-Benz',
    AUDI = 'Audi',
    LEXUS = 'Lexus',
    PORSCHE = 'Porsche',
    MASERATI = 'Maserati',
    JAGUAR = 'Jaguar',
    LAND_ROVER = 'Land Rover',
    VOLVO = 'Volvo',
    ALFA_ROMEO = 'Alfa Romeo',
    TESLA = 'Tesla',
    GENESIS = 'Genesis',
    INFINITI = 'Infiniti',
    CADILLAC = 'Cadillac',
    BUICK = 'Buick',
    LINCOLN = 'Lincoln',
    BENTLEY = 'Bentley',
    FERRARI = 'Ferrari',
    LAMBORGHINI = 'Lamborghini',
    ASTON_MARTIN = 'Aston Martin',
    ROLLS_ROYCE = 'Rolls-Royce',
    BUGATTI = 'Bugatti',
  }